<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-2LONNQF" ignored="1" name="Parallel Run -IE" tests="1" failures="1" timestamp="15 Aug 2020 10:06:46 GMT" time="298.722" errors="0">
  <testcase name="LoginCheck" time="263.715" classname="com.qa.TestClass.TestClass">
    <failure type="java.lang.AssertionError" message="expected [ContactsNew] but found [Contacts]">
      <![CDATA[java.lang.AssertionError: expected [ContactsNew] but found [Contacts]
at com.qa.TestClass.TestClass.LoginCheck(TestClass.java:72)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- LoginCheck -->
  <testcase name="invalidDataLogin" time="0.0" classname="com.qa.TestClass.TestClass">
    <ignored/>
  </testcase> <!-- invalidDataLogin -->
</testsuite> <!-- Parallel Run -IE -->
