<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="2" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Parallel" duration-ms="298722" started-at="2020-08-15T10:01:47Z" finished-at="2020-08-15T10:06:46Z">
    <groups>
    </groups>
    <test name="Parallel Run-Chrome" duration-ms="81971" started-at="2020-08-15T10:01:47Z" finished-at="2020-08-15T10:03:09Z">
      <class name="com.qa.TestClass.TestClass">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.qa.TestClass.TestClass@78411116]" name="setUp" is-config="true" duration-ms="27909" started-at="2020-08-15T10:01:48Z" finished-at="2020-08-15T10:02:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="LoginCheck()[pri:0, instance:com.qa.TestClass.TestClass@78411116]" name="LoginCheck" duration-ms="50980" started-at="2020-08-15T10:02:16Z" finished-at="2020-08-15T10:03:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ContactsNew] but found [Loading...]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ContactsNew] but found [Loading...]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.TestClass.TestClass.LoginCheck(TestClass.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginCheck -->
      </class> <!-- com.qa.TestClass.TestClass -->
    </test> <!-- Parallel Run-Chrome -->
    <test name="Parallel Run -IE" duration-ms="298722" started-at="2020-08-15T10:01:47Z" finished-at="2020-08-15T10:06:46Z">
      <class name="com.qa.TestClass.TestClass">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.qa.TestClass.TestClass@47b2e9e1]" name="setUp" is-config="true" duration-ms="33465" started-at="2020-08-15T10:01:48Z" finished-at="2020-08-15T10:02:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[IE]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="LoginCheck()[pri:0, instance:com.qa.TestClass.TestClass@47b2e9e1]" name="LoginCheck" duration-ms="263715" started-at="2020-08-15T10:02:22Z" finished-at="2020-08-15T10:06:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ContactsNew] but found [Contacts]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ContactsNew] but found [Contacts]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.TestClass.TestClass.LoginCheck(TestClass.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginCheck -->
      </class> <!-- com.qa.TestClass.TestClass -->
    </test> <!-- Parallel Run -IE -->
  </suite> <!-- Parallel -->
</testng-results>
